### ISSUE TITLE
403 Forbidden Help

### ISSUE THREAD

**Issue by alibehroozi** [vvrahul/google-plus-post-share-api-php#1]
Hey dear
I'm getting 403 Forbidden Like below:
`{ "error": { "errors": [ { "domain": "global", "reason": "forbidden", "message": "Forbidden" } ], "code": 403, "message": "Forbidden" } } `
Please Help What Should I do to post on google plus profile
Thanks

**Comment by vvrahul** [comment]
please provide the user in` $user_id = 'your google plus user id';` index.php file
